#!/usr/bin/env bash
set -eo pipefail

ensure_pkg -i Ubuntu apt fish
fish -c 'functions -q fisher' >/dev/null 2>&1 || {
  fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
  fish -c 'fisher update'
}
