#theme = "solarized-dark"
#icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 15.0
alert = 8.0
format = "{available} Free"

[[block]]
block = "networkmanager"
interface_name_include = ["wlp.*", "enp.*"]

[[block]]
block = "custom"
command = ''' test -d /proc/sys/net/ipv4/conf/wg-mullvad && echo '{"icon":"toggle_on","state":"Good", "text": "VPN"}' ||echo '{"icon":"toggle_off", "text": "VPN"}' '''
on_click = ''' test -d /proc/sys/net/ipv4/conf/wg-mullvad && mullvad disconnect || mullvad connect '''
json = true
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}%"
format_swap = "{swap_used_percents}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
hide_missing = true
allow_missing = true

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %R"
