#!/usr/bin/env bash
set -eo pipefail

ensure_pkg -i Ubuntu apt libdbus-1-dev
ensure_pkg -i Ubuntu apt libssl-dev
ensure_pkg -i Ubuntu apt pulseaudio
test -f ~/.cargo/bin/i3status-rs || cargo install --git https://github.com/greshake/i3status-rust i3status-rs
