#!/bin/bash
CUR=$(xbacklight)

if [ $(echo ${CUR} \< 11 | bc) -eq 1 ]; then
  if [ $(echo ${CUR} \< 1 | bc) -eq 1 ]; then
    xbacklight -set 0
  else
    # Minimum visible brightness
    xbacklight -set 1
  fi
else
  xbacklight -10
fi
